title: Endless Access Community Handbook
description: Documentation for the Endless Access community itself
theme: just-the-docs
url: https://Endless-Access-Community.github.io/handbook
permalink: pretty

# Just the Docs
logo: "/assets/images/logo.svg"
color_scheme: light

callouts:
  note:
    title: Note
    color: cyan
  warning:
    title: Heads up!
    color: orange

aux_links:
  Website: https://www.endlessos.org/game-making
  Discord: https://discord.gg/joinendless
  GitHub: https://github.com/Endless-Access-Community

aux_links_new_tab: true

nav_external_links:
  - title: Edit on GitHub
    url: https://github.com/Endless-Access-Community/handbook

nav_external_links_new_tab: true
