title: Endless Access Community Handbook
description: Documentation for the Endless Access community itself
theme: just-the-docs
url: https://endless-access-community.github.io/handbook
permalink: pretty

#################
# Just the Docs #
#################

logo: "/assets/images/logo.svg"
color_scheme: light

callouts:
  note:
    title: Note
    color: cyan
  warning:
    title: Heads up!
    color: orange

aux_links:
  Website: https://www.endlessos.org/game-making
  Discord: https://discord.gg/joinendless
  GitHub: https://github.com/Endless-Access-Community

aux_links_new_tab: true

nav_external_links:
  - title: Code of Conduct
    url: https://github.com/Endless-Access-Community/.github/blob/main/CODE_OF_CONDUCT.md

nav_external_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: Edit Page on GitHub
gh_edit_repository: https://github.com/Endless-Access-Community/handbook
gh_edit_branch: main
gh_edit_view_mode: edit
